{% set name = "syny" %}
{% set version = "1.1a" %}
{% set sha256 = "fb67d94d0e343eb0c937e201099ddee408f5088f06e3ec563163cd4d4c86a02a" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/PombertLab/SYNY/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
  - {{ pin_subpackage('syny', max_pin='x') }}
  skip: true  # [win]

requirements:
  host:
    - perl >=5.32
    - python
  run:
    - perl >=5.32
    - python
    - matplotlib-base
    - pandas
    - seaborn
    - scipy
    - libgd
    - perl-perlio-gzip
    - perl-getopt-argvfile
    - perl-clone
    - perl-config-general
    - perl-font-ttf
    - perl-list-moreutils
    - perl-math-bezier
    - perl-math-round 
    - perl-math-vecstat
    - perl-params-validate
    - perl-readonly 
    - perl-regexp-common
    - perl-set-intspan
    - perl-statistics-basic
    - perl-SVG
    - perl-gd
    - perl-text-format
    - perl-text-roman
    - minimap2 >=2.28
    - mashmap >=3.1.3
    - diamond >=2.1.9
    - circos

test:
  commands:
    - run_syny.pl --version
    - circos -v
    - minimap2 --version
    - mashmap --version
    - diamond --version

about:
  home: https://github.com/PombertLab/SYNY
  license: MIT
  summary: "Genome collinearity inferences"

extra:
  recipe-maintainers:
    - Pombert-JF
